Update github-actions-script.yml

diff --git a/.github/workflows/github-actions-script.yml b/.github/workflows/github-actions-script.yml
--- a/.github/workflows/github-actions-script.yml
+++ b/.github/workflows/github-actions-script.yml
@@ -27,3 +27,23 @@ jobs:
       with:
         commit_message: Apply php-cs-fixer changes
         file_pattern: '*.pdf'
+
+    - name: Remove output.tex file
+      run: |
+        if [ -f output.tex]; then
+          rm output.tex
+          echo "output.tex file removed."
+        else
+          echo "output.tex file not found."
+          exit  1
+        fi
+      shell: bash
+      
+    - name: Commit changes
+      run: |
+        git config --global user.name 'GitHub Actions'
+        git config --global user.email 'actions@github.com'
+        git add output.tex
+        git commit -m "Remove output.tex file"
+        git push
+      shell: bash
